---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    DeletionPolicy: Delete
    Properties:
      AvailabilityZone: ap-southeast-2b
      ImageId: ami-0c6120f461d6b39e9
      InstanceType: t2.nano
      KeyName: blind-mac
      SecurityGroups:
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH_CONNECTION
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp

Outputs:
  MyInstance:
    Value: !Ref MyInstance
    Description: Amazon MyInstance
    Export:
      Name: !Sub "${AWS::StackName}-PublicIp"
  PublicIp:
      Description: Server Public IP
      Value: !GetAtt MyInstance.PublicIp
      Export:
        Name: !Sub "${AWS::StackName}-PublicIpx"
